# -*- coding: utf-8 -*-
"""ChatBotProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OrEnIv3BUDVip_-ORyL30SLPY4BZTrl
"""

# Description: This is a chat bot program

#import the library
from nltk.chat.util import Chat, reflections

pairs = [
    ['my name is (.*)', ['hi %1']],
    ['(hi|hello|hey|hola)',['hey there', 'hi there','hayyy']],
    ['(.*) in (.*) is fun',['%1 in %2 is indeed fun']],
    ['(.*).created you?',['randerson112358 dis using NLTK']],
    ['how is the weather in (.*) right now?', ['the weather in %1 is amazing like always']],
    ['(.*)help(.*)', ['I can help you']],
    ['how are you (.*) ?', ["I'm doing very well", "i am great !"]],
    ["(.*)(sports|game|sport)(.*)",["I'm a very big fan of Basketball",]],
    ['(.*) your name ?', ['my name is ChatBot']],
    ['(.*) (location|city) ?', ['Tokyo, Japan',]],
    ["how (.*) health (.*)", ["Health is very important, but I am a computer, so I don't need to worry about my health ",]],
    ["(.*)(sports|game|sport)(.*)",["I'm a very big fan of Basketball",]],
    ["who (.*) (moviestar|actor|actress)?", ["Zendaya"]],
    ["quit",["Bye for now. See you soon :) ","It was nice talking to you. See you soon :)"]],
    ["(.*)", ['That is nice to hear']]
]

reflections

my_dummy_reflections = {
    'go' : 'gone',
    'hello' : 'hey there'
}

chat = Chat(pairs, my_dummy_reflections)
#chat._substitute('go hello')
chat.converse()